name: semgrep-develop

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test-develop:
    runs-on: ubuntu-latest
    name: test-develop
    steps:
    - uses: actions/checkout@v2
    - name: test
      id: test
      uses: returntocorp/semgrep-rules-test-action@master
